---
title: "cdl_training_schools"
output: html_document
date: "2025-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Data wrangling
library(tidyverse)   
library(janitor)     
library(readxl)    
library(dplyr)
library(lubridate)
library(data.table)
library(readr)
library(DBI)
library(duckdb)
library(tidycensus)
library(tigris)
library(tidyr)

# Mapping and other visualizations
library(sf)          
library(tmap)        
library(leaflet)     
library(RColorBrewer)
library(ggstream)
library(ggplot2)
library(htmlwidgets)
library(treemapify)
```


```{r}
cdl_in_review <- read_csv("fmcsa_in_review.csv") %>%
  clean_names()

cdl_removed <- read_csv("fmcsa_removed_jan_6_2026.csv") %>%
  clean_names()
```

```{r}
cdl_in_review_wi <- cdl_in_review %>%
  filter(physical_state == "Wisconsin (WI)")

cdl_removed_wi <- cdl_removed %>%
  filter(physical_state == "Wisconsin (WI)")

write_csv(cdl_in_review_wi, "cdl_in_review_wi.csv")
write_csv(cdl_removed_wi, "cdl_removed_wi.csv")
```

